version: '3'

services:
    bot: 
        build: ./src
        # command: nodemon --inspect bot.js
        env_file: 
            - .env
        volumes:
            - './src:/app'
            - './local-db:/local-db'
        restart: unless-stopped
